src/Ingewikkeld/LinkTuesdayBundle/Entity/Link.php
<?php

namespace Ingewikkeld\LinkTuesdayBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Buzz\Browser;

/**
 * @ORM\Table(name="Link")
 * @ORM\Entity(repositoryClass="Ingewikkeld\LinkTuesdayBundle\Entity\LinkRepository")
 */
class Link
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $uri;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $full_uri;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $title;

    /**
     * @var ArrayCollection
     *
     * @ORM\OneToMany(targetEntity="\Ingewikkeld\LinkTuesdayBundle\Entity\Tweet", mappedBy="link")
     * @ORM\OrderBy({"date" = "ASC"})
     */
    protected $tweets;

    /**
     * Constructor. Sets up the tweets property as a new ArrayCollection
     */
    public function __construct()
    {
        $this->tweets = new ArrayCollection();
    }

    /**
     * Get the id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set the id
     *
     * @param int $id
     * @return void
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    public function getUri()
    {
        return $this->uri;
    }

    public function setUri($uri)
    {
        $this->uri = trim($uri);
    }

    public function getFullUri()
    {
        return $this->full_uri;
    }

    public function setFullUri($full_uri)
    {
        $this->full_uri = $full_uri;
        $this->followUri();
    }

    public function getTitle()
    {
        return $this->title;
    }

    public function setTitle($title)
    {
        $this->title = $title;
    }

    public function getTweets()
    {
        return $this->tweets;
    }

    public function getFirstTweet()
    {
      $tweets = $this->getTweets();
      return $tweets[0];
    }

    public function followUri()
    {
        $browser = new Browser();
        try {
            $response = $browser->get($this->getFullUri());

            $dom = $response->toDomDocument();
            $sxml = simplexml_import_dom($dom);

            $titles = $sxml->xpath('//title');
        } catch(\Exception $e) {
            $titles = array();
        }

        if (count($titles) > 0)
        {
            $title = (string) $titles[0];
        }
        else
        {
            $title = $this->getFullUri();
        }
        $this->setTitle(trim($title));
    }

    /**
     * Get only the domain part out of the full uri
     *
     * @return string
     */
    public function getDomain()
    {
        $fullUri = $this->getFullUri();
        $parts = explode('/', $fullUri);
        if (isset($parts[2])) {
            return $parts[2];
        }
    }
}

src/Ingewikkeld/LinkTuesdayBundle/Entity/Tweet.php
<?php

namespace Ingewikkeld\LinkTuesdayBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Ingewikkeld\LinkTuesdayBundle\Entity\Link;

/**
 * @ORM\Table(name="Tweet")
 * @ORM\Entity(repositoryClass="Ingewikkeld\LinkTuesdayBundle\Entity\TweetRepository")
 */
class Tweet
{
    /**
     * @var integer
     *
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $uri;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $content;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=25)
     */
    protected $user;

    /**
     * @var string
     *
     * @ORM\Column(type="string", length=255)
     */
    protected $profile_image;

    /**
     * @var \DateTime
     *
     * @ORM\Column(type="datetime")
     */
    protected $date;

    /**
     * @var array
     *
     * @ORM\ManyToOne(targetEntity="Link", inversedBy="tweet")
     * @ORM\JoinColumn(name="link_id", referencedColumnName="id", onDelete="CASCADE")
     */
    protected $link;

    public function getId()
    {
        return $this->id;
    }

    public function setId($id)
    {
        $this->id = $id;
    }

    public function getUri()
    {
        return $this->uri;
    }

    public function setUri($uri)
    {
        $this->uri = $uri;
    }

    public function getContent()
    {
        return $this->content;
    }

    public function setContent($content)
    {
        $this->content = $content;
    }

    public function getLink()
    {
        return $this->link;
    }

    public function setLink(Link $link)
    {
        $this->link = $link;
    }

    public function getUser()
    {
        return $this->user;
    }

    public function setUser($user)
    {
        $this->user = $user;
    }

    public function getProfileImage()
    {
        return $this->profile_image;
    }

    public function setProfileImage($profile_image)
    {
        $this->profile_image = $profile_image;
    }

    public function setDate(\DateTime $date)
    {
        $this->date = $date;
    }

    public function getDate()
    {
        return $this->date;
    }

    public function getDisplayDate()
    {
      return $this->date->format('c');
    }
    
}

src/Ingewikkeld/LinkTuesdayBundle/Controller/LinkController.php
<?php

namespace Ingewikkeld\LinkTuesdayBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Method;

class LinkController extends Controller
{
    /**
     * @Route("/", name="lt_homepage")
     * @Method({"GET"})
     * @Template()
     */
    public function indexAction()
    {
        $em = $this->get('doctrine.orm.default_entity_manager');

        return array(
            'recent'    => $em->getRepository('IngewikkeldLinkTuesdayBundle:Link')->getMostRecentLinks(),
            'top'       => $em->getRepository('IngewikkeldLinkTuesdayBundle:Link')->getMostPopularLinks(),
            'weektop'   => $em->getRepository('IngewikkeldLinkTuesdayBundle:Link')->getMostPopularLinksSince(date('d-m-Y', time()-(86400*7))),
        );
    }

    /**
     * @Route("/search", name="lt_search")
     * @Template()
     */
    public function searchAction()
    {
        $em = $this->get('doctrine.orm.default_entity_manager');

        return array(
            'results' => $em->getRepository('IngewikkeldLinkTuesdayBundle:Tweet')->search($this->getRequest()->get('term')),
            'term' => $this->getRequest()->get('term')
        );
    }

    /**
     * @Route("/feed", name="lt_feed")
     * @Method({"GET"})
     * @Template()
     */
    public function rssAction()
    {
      $em = $this->get('doctrine.orm.default_entity_manager');

      $items = $em->getRepository('IngewikkeldLinkTuesdayBundle:Link')->getMostRecentLinks();

      $templateItems = array();
      foreach($items as $item)
      {
        $templateItems[] = $item[0];
      }

      return array('items' => $templateItems, 'date' => date('c'));
    }
}

src/Ingewikkeld/LinkTuesdayBundle/Resources/views/Link/index.html.twig
{% extends '::base.html.twig' %}

{% block title %}Linktuesday{% endblock %}

{% block body %}
        <div class="yui-u first">
            <h2>Recent links</h2>
            <div class="inner">
            {% for row in recent %}
              {% include 'IngewikkeldLinkTuesdayBundle:Link:linkdetail.html.twig' with {'row': row, 'type':'recent'} %}
            {% endfor %}
            </div>
        </div>
        <div class="yui-u">
            <h2>Most popular links</h2>
            <div class="inner">
            {% for row in top %}
              {% include 'IngewikkeldLinkTuesdayBundle:Link:linkdetail.html.twig' with {'row': row, 'type':'top'} %}
            {% endfor %}
            </div>
        </div>
        <div class="yui-u">
            <h2>Popular this week</h2>
            <div class="inner">
            {% for row in weektop %}
              {% include 'IngewikkeldLinkTuesdayBundle:Link:linkdetail.html.twig' with {'row': row, 'type':'weektop'} %}
            {% endfor %}
            </div>
        </div>
{% endblock %}

src/Ingewikkeld/LinkTuesdayBundle/Resources/views/Link/linkdetail.html.twig
{% set link = row.0 %}
<div class="link">
    <div class="tweetcount"><a href="javascript://" onClick="$('#tweets_for_{{ link.id }}_in_{{ type }}').toggle(300);" title="see the tweets about this link">{{ row.tweetCount }}</a></div>
    <div class="linktitle"><a href="javascript://" onClick="$('#tweets_for_{{ link.id }}_in_{{ type }}').toggle(300);" title="see the tweets about this link">{{ link.title }}</a></div>
    <div class="actuallink"><a href="{{ link.fullUri }}" target="_blank" title="open this link in a new window">{{ link.domain }}</a></div>
    <br /><br clear="all" />
    <div id="tweets_for_{{ link.id }}_in_{{ type }}" class="tweetcollection">
    {% for tweet in link.tweets %}
            {% include 'IngewikkeldLinkTuesdayBundle:Link:tweetdetail.html.twig' with {'tweet': tweet} %}
    {% endfor %}
    </div>
</div>

src/Ingewikkeld/LinkTuesdayBundle/Resources/views/Link/rss.html.twig
<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:wfw="http://wellformedweb.org/CommentAPI/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:slash="http://purl.org/rss/1.0/modules/slash/"
	>
<channel>
	<title>LinkTuesday.com</title>
	<atom:link href="http://linktuesday.com/feed/" rel="self" type="application/rss+xml" />
	<link>http://linktuesday.com</link>
	<description>Interesting links posted on Twitter with the #linktuesday hashtag</description>
	<lastBuildDate>{{ date }}</lastBuildDate>
	<generator>http://linktuesday.com/</generator>
	<language>en</language>

    {% for item in items %}
    <item>
		<title>{{ item.title }}</title>
		<link>{{ item.full_uri }}</link>
		<pubDate>{{ item.FirstTweet.DisplayDate }}</pubDate>
		<dc:creator>{{ item.FirstTweet.user }}</dc:creator>
		<guid isPermaLink="false">{{ item.full_uri }}</guid>
		<description><![CDATA[{{ item.title }}]]></description>
        <content:encoded><![CDATA[{{ item.title }}]]></content:encoded>
    </item>
    {% endfor %}
    
	</channel>
</rss>

src/Ingewikkeld/LinkTuesdayBundle/Resources/views/Link/search.html.twig
{% extends '::base.html.twig' %}

{% block title %}Linktuesday - Search - {{ term }}{% endblock %}

{% block body %}
    <div class="yui-u first">
        <h2>Search result</h2>
        <div class="inner">
            {% for row in results %}
                {% include 'IngewikkeldLinkTuesdayBundle:Link:tweetdetail.html.twig' with {'tweet': row, 'type':'recent'} %}
            {% endfor %}
        </div>
    </div>
{% endblock %}

src/Ingewikkeld/LinkTuesdayBundle/Resources/views/Link/tweetdetail.html.twig
<div class="tweet"><img src="{{ tweet.profileImage }}" alt="{{ tweet.user }}" align="left"/> {{ tweet.content }} <br />
<span class="meta">by {{ tweet.user }} on {{ tweet.date|date('d-m-Y') }}</span><br />
</div>